# Generated by Django 2.2.7 on 2019-11-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Sport',
        ),
    ]
